name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    name: Build with ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    environment: staging
    env:
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}
      ONE_MAP_API_KEY: ${{ secrets.ONE_MAP_API_KEY }}
      FORCE_LOCAL_DB: 1
      SENTRY_SUPPRESS_TURBOPACK_WARNING: 1
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v5
      - name: Debug - Check if secrets are loaded
        run: |
          echo "Checking secret availability..."
          if [ -z "$CLERK_SECRET_KEY" ]; then echo "❌ CLERK_SECRET_KEY is empty"; else echo "✅ CLERK_SECRET_KEY is set"; fi
          if [ -z "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" ]; then echo "❌ NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY is empty"; else echo "✅ NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY is set"; fi
          if [ -z "$NEXT_PUBLIC_CLERK_SIGN_IN_URL" ]; then echo "❌ NEXT_PUBLIC_CLERK_SIGN_IN_URL is empty"; else echo "✅ NEXT_PUBLIC_CLERK_SIGN_IN_URL is set"; fi
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run build

  # test:
  #   strategy:
  #     matrix:
  #       node-version: [20.x]

  #   name: Run all tests
  #   runs-on: ubuntu-latest
  #   environment: staging
  #   env:
  #     CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
  #     NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
  #     NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}
  #     ONE_MAP_API_KEY: ${{ secrets.ONE_MAP_API_KEY }}
  #     FORCE_LOCAL_DB: 1
  #     SENTRY_SUPPRESS_TURBOPACK_WARNING: 1
  #     NODE_ENV: test

  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0 # Retrieve Git history, needed to verify commits
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: npm
  #     - run: npm ci

  #     - name: Build Next.js for E2E tests
  #       run: npm run build

  #     - if: github.event_name == 'pull_request'
  #       name: Validate all commits from PR
  #       run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  #     - name: Linter
  #       run: npm run lint

  #     - name: Type checking
  #       run: npm run check-types

  #     - name: Run unit tests
  #       run: npm run test -- --coverage

  #     # - name: Upload coverage reports to Codecov
  #     #   uses: codecov/codecov-action@v5
  #     #   env:
  #     #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  #     - name: Install Playwright (used for Storybook and E2E tests)
  #       run: npx playwright install --with-deps

  #     # - name: Run storybook tests
  #     #   run: npm run test-storybook:ci

  #     - name: Run E2E tests
  #       run: npx percy exec -- npm run test:e2e
  #       env:
  #         PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  #         CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

  #     - uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: test-results
  #         path: test-results/
  #         retention-days: 7
